### ISSUE TITLE
How to refresh if bound data changes

### ISSUE THREAD

**Issue by pbrickell** [benib/aurelia-leaflet#1]
Can I expect the map to reposition if I change the map options centre? I want the user to be able to centre the map by selecting a location in another control in my page. TIA.

**Comment by pbrickell** [comment]
Never mind. I see what I need to do now. Sorry.

**Comment by benib** [comment]
@pbrickell nice that you found out. Can you post your solution here for reference?

**Comment by pbrickell** [comment]
Sure. I simply misunderstood how to use the classes provided. What I wanted was something like this in my component...

```
constructor(element, eventAggregator) {
    this.element = element;
    this.eventAggregator = eventAggregator;

    this.eventAggregator.subscribe('aurelia-leaflet', payload=>{
        if(payload.type==='load') {
            this.map = payload.map;
        }
    });
}

locationChanged() {
    this.map.panTo([this.location.lat, this.location.lng]);
}
```
