### ISSUE TITLE
leaflet in aurelia-cli

### ISSUE THREAD

**Issue by schmarre** [benib/aurelia-leaflet#10]
Hi there and thanks for your plugin!
I would like to integrate it into a aurelia-cli project. I'm having problems setting it up in the aurelia.json file. Would you be able to give instructions?
Thanks in advance!

**Comment by benib** [comment]
Maybe the solution posted here works for you as well? https://github.com/benib/aurelia-leaflet/issues/8

**Comment by schmarre** [comment]
Yes, indeed the link and project example in https://github.com/diegohb/aurelia-leaflet-cluster did help to get it working
Thanks!

**Comment by schmarre** [comment]
Now, next question: Would you be able to enhance to plugin with an bindable address? Meaning converting an address to lat - lng values in order to set markers?
Something like in this link: https://github.com/Vheissu/aurelia-google-maps.

**Comment by benib** [comment]
@schmarre I'd will not add geocoding to aurelia-leaflet for these reasons:

- there are a lot of geocoding services and people have their own preferences here
- building abstraction to configure different services is out of the scope of this project
- handling the case where geocoding fails is out of the scope of this project

So I will keep this project as simple as possible. Compiling data to then show on the map should be done somewhere else, aurelia-leaflet can then be used to display this data no matter where it is coming from.

For any future feature requests, please open a separate issue.
