### ISSUE TITLE
Make the dependencies more explicit.

### ISSUE THREAD

**Issue by shaunluttin** [benib/aurelia-leaflet#5]
We manually had to map the dependency on `aurelia-event-aggregator`. It would be nice to do this automatically on `jspm install github:benib/aurelia-leaflet`.

config.js

```
map: {
    "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.2.1"
}
```

**Comment by benib** [comment]
fixed with version `1.0.0`

**Comment by shaunluttin** [comment]
Thank you for maintaining the project. :) We're using it on https://www.greenearth.game and will be upgrading to your most recent release.

**Comment by benib** [comment]
@shaunluttin great to see it used in the wild. Please file issues if you have any problems.

Please consider using another source than the default one for the map tiles. See the OpenStreetMap tile usage policy: http://wiki.openstreetmap.org/wiki/Tile_usage_policy
