### ISSUE TITLE
Can't use the plugin in my aurelia app

### ISSUE THREAD

**Issue by ghost** [benib/aurelia-leaflet#9]
Hi,
i would really like to use leaflet in my app, but aurelia makes it really hard to do so. My concern is, that the line `aurelia.use.plugin('benib/aurelia-leaflet');` my not be right. Or am i doing something wrong?

Best regards

**Comment by benib** [comment]
The line is correct. But its not the only thing you have to do.
Can you explain what does not work as you expect and add some information about what you did?

**Comment by benib** [comment]
closing as reporters account doesn't exist anymore.
